# XOR RELU forward propagation
> A programming introduc

- toc: true 
- badges: true
- comments: true
- author: Nipun Batra
- categories: [ML]

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
X = np.array([[0, 0],
             [0, 1],
             [1, 0],
             [1, 1]
             ])

y = np.array([[0], [1], [1], [0]])

In [3]:
X.shape, y.shape

((4, 2), (4, 1))

In [7]:
N, N_0 = X.shape
N, N_2 = y.shape
N_1 = 2

In [8]:
W = [None, np.array([[1, 1], [1, 1]]), np.array([[1, -2]])]

b = [None, np.array([[0], [-1]]), np.array([[0]])]
B = [None]


In [13]:
A = [X]
A.extend([None]*len(W))
Z = [None]*(len(W)+1)

assert(A[0].shape==(N, N_0))


In [14]:
for i in range(1, len(W)):
    print(i)
    Z[i] = A[i-1]@(W[i].T) + b[i].T
    A[i] = Z[i]
    A[i][A[i]<0] = 0
    print(Z[i], A[i])

1
[[0 0]
 [1 0]
 [1 0]
 [2 1]] [[0 0]
 [1 0]
 [1 0]
 [2 1]]
2
[[0]
 [1]
 [1]
 [0]] [[0]
 [1]
 [1]
 [0]]


In [15]:
np.allclose(A[i], y)

True

Excellent, now let us start from random weight initialisations and use backprop to come to our result

In [128]:
shapes = [X.shape[1], 2, 1]
activations = [None, 'sigmoid','sigmoid']


def sigmoid(z):
    return 1./(1+np.exp(-z))

def relu(z):
    temp = z.copy()
    temp[temp<0] = 0
    return temp

activation_func = {'sigmoid':sigmoid, 'relu':relu}

N, N0 = X.shape
N1 = 2
N2 = 1

W = [None]*len(shapes)
b = [None]*len(shapes)

np.random.seed(0)

for i in range(1, len(shapes)):
    W[i] = np.random.randn(shapes[i], shapes[i-1])
    b[i] = np.random.randn(shapes[i], 1)
    
Z = [None]*(len(W)+1)

A = [X]
A.extend([None]*len(W))

for i in range(1, len(W)):
    print(i)
    Z[i] = A[i-1]@(W[i].T) + b[i].T
    A[i] = activation_func[activations[i]](Z[i])
    print(Z[i], A[i])

loss = (-y.T@np.log(A[2]) - (1-y).T@np.log(1-A[2])).squeeze()
print(loss)

1
[[ 1.86755799e+00 -9.77277880e-01]
 [ 2.26771520e+00  1.26361532e+00]
 [ 3.63161034e+00  1.46010423e-03]
 [ 4.03176754e+00  2.24235330e+00]] [[0.86617546 0.27343225]
 [0.9061677  0.77964784]
 [0.97420925 0.50036503]
 [0.98256638 0.9039889 ]]
2
[[0.67833848]
 [0.63971526]
 [0.74663222]
 [0.69348085]] [[0.66336776]
 [0.65468909]
 [0.67844443]
 [0.66674081]]
2.9991464995409807


In [129]:
epochs = 5000
alpha = 1.4

del_Z = [None]*(len(W))
del_A = [None]*(len(W))
del_W = [None]*(len(W))
del_b = [None]*(len(W))

for i in range(epochs):
    
    del_A[2] = -np.multiply(y, A[2]) + np.multiply((1-y), (1-A[2]))
    del_Z[2] = A[2]-y
    del_W[2] = (A[2]-y).T@A[1]
    del_b[2] = (del_Z[2].sum(axis=0)).reshape(-1, 1)
    del_A[1] = del_Z[2]@W[2]
    del_Z[1]  = np.multiply(del_A[1], sigmoid(Z[1])*(1-sigmoid(Z[1])))
    del_W[1] = del_Z[1].T@A[1]
    del_b[1] = (del_Z[1].sum(axis=0)).reshape(-1, 1)
    
    for i in range(1, len(shapes)):
        W[i] = W[i] - alpha*del_W[i]
        b[i] = b[i] - alpha*del_b[i]
        #print(W, b)
        
    for i in range(1, len(W)):
        Z[i] = A[i-1]@(W[i].T) + b[i].T
        A[i] = activation_func[activations[i]](Z[i])

    loss = (-y.T@np.log(A[2]) - (1-y).T@np.log(1-A[2])).squeeze()
    print(i, loss)

2 3.643007712117819
2 5.061975442873277
2 5.397032652638153
2 4.971954914819463
2 4.542927652636707
2 4.160104077880978
2 3.9709893045883384
2 3.558802796896787
2 3.411465781938481
2 3.1299791436904845
2 3.0316594743885377
2 2.918418015634867
2 2.8697201968194603
2 2.828433362276911
2 2.8076196570974083
2 2.7923123744230622
2 2.7837322169043386
2 2.7778688355104983
2 2.774272287274391
2 2.771901256177917
2 2.770286869303706
2 2.7692224950008857
2 2.768392082710145
2 2.767818911023342
2 2.7672997172592364
2 2.7669096771941515
2 2.766514640689248
2 2.766189782638428
2 2.765843408784815
2 2.765537552303513
2 2.765207854139728
2 2.7649019774361676
2 2.764573992693615
2 2.7642592881231733
2 2.7639247558423996
2 2.7635961567331027
2 2.763249457952875
2 2.7629031540954063
2 2.7625396838068688
2 2.7621721615937576
2 2.761787648416566
2 2.7613953126988613
2 2.760985510327375
2 2.760564525065699
2 2.760125050249859
2 2.7596712575990168
2 2.759197485320219
2 2.758706348614301
2 2.7581933280363797

2 1.439147498610053
2 1.4386850643852274
2 1.4382295500556102
2 1.4377808146251674
2 1.437338720699627
2 1.4369031343753789
2 1.436473925132445
2 1.4360509657313163
2 1.435634132113533
2 1.4352233033058142
2 1.4348183613276122
2 1.43441919110193
2 1.4340256803692975
2 1.4336377196047296
2 1.4332552019375981
2 1.4328780230742537
2 1.4325060812233188
2 1.4321392770235262
2 1.4317775134740094
2 1.4314206958669518
2 1.431068731722485
2 1.4307215307257772
2 1.430379004666193
2 1.430041067378475
2 1.4297076346858482
2 1.4293786243449846
2 1.4290539559927578
2 1.4287335510947146
2 1.4284173328951995
2 1.4281052263690786
2 1.4277971581749989
2 1.4274930566101176
2 1.4271928515662635
2 1.4268964744874715
2 1.4266038583288316
2 1.4263149375166257
2 1.4260296479096815
2 1.425747926761921
2 1.4254697126860465
2 1.4251949456183368
2 1.4249235667845004
2 1.4246555186665697
2 1.4243907449707662
2 1.4241291905963438
2 1.4238708016053503
2 1.423615525193275
2 1.4233633096605738
2 1.4231141043850113
2 1

2 1.3946934307114525
2 1.3946780362367406
2 1.3946626969613343
2 1.3946474125949493
2 1.3946321828492962
2 1.3946170074380644
2 1.3946018860769112
2 1.39458681848344
2 1.3945718043771795
2 1.3945568434795814
2 1.39454193551399
2 1.3945270802056304
2 1.3945122772816005
2 1.394497526470845
2 1.3944828275041457
2 1.3944681801141017
2 1.3944535840351222
2 1.394439039003404
2 1.394424544756919
2 1.3944101010353989
2 1.394395707580323
2 1.3943813641349039
2 1.3943670704440674
2 1.3943528262544427
2 1.3943386313143546
2 1.3943244853737944
2 1.3943103881844237
2 1.3942963394995438
2 1.3942823390740973
2 1.3942683866646446
2 1.3942544820293545
2 1.3942406249279908
2 1.3942268151219008
2 1.3942130523740004
2 1.3941993364487604
2 1.3941856671121964
2 1.3941720441318561
2 1.3941584672768066
2 1.394144936317621
2 1.3941314510263658
2 1.3941180111765934
2 1.394104616543325
2 1.3940912669030412
2 1.394077962033671
2 1.3940647017145795
2 1.394051485726554
2 1.3940383138517984
2 1.394025185873914
2 1.3

2 1.3900465779195912
2 1.390043466458264
2 1.390040360167593
2 1.3900372590347683
2 1.3900341630470163
2 1.3900310721916098
2 1.3900279864558611
2 1.3900249058271243
2 1.390021830292795
2 1.3900187598403106
2 1.39001569445715
2 1.3900126341308279
2 1.3900095788489075
2 1.3900065285989878
2 1.3900034833687078
2 1.3900004431457504
2 1.3899974079178348
2 1.3899943776727206
2 1.3899913523982095
2 1.3899883320821398
2 1.3899853167123934
2 1.3899823062768846
2 1.3899793007635726
2 1.3899763001604548
2 1.3899733044555673
2 1.3899703136369792
2 1.3899673276928062
2 1.3899643466111993
2 1.389961370380346
2 1.3899583989884716
2 1.389955432423844
2 1.389952470674762
2 1.3899495137295665
2 1.3899465615766349
2 1.3899436142043822
2 1.3899406716012588
2 1.3899377337557532
2 1.3899348006563912
2 1.3899318722917346
2 1.3899289486503812
2 1.3899260297209672
2 1.389923115492163
2 1.3899202059526745
2 1.389917301091245
2 1.3899144008966555
2 1.3899115053577167
2 1.3899086144632824
2 1.3899057282022356
2 

2 1.3889048129804924
2 1.3889033127882766
2 1.3889018143331424
2 1.3889003176120749
2 1.3888988226220669
2 1.3888973293601201
2 1.388895837823246
2 1.388894348008456
2 1.388892859912771
2 1.388891373533221
2 1.3888898888668404
2 1.3888884059106714
2 1.3888869246617639
2 1.388885445117173
2 1.3888839672739586
2 1.388882491129193
2 1.38888101667995
2 1.3888795439233146
2 1.3888780728563732
2 1.3888766034762208
2 1.3888751357799636
2 1.3888736697647075
2 1.3888722054275697
2 1.388870742765671
2 1.3888692817761428
2 1.3888678224561173
2 1.388866364802738
2 1.3888649088131526
2 1.3888634544845169
2 1.3888620018139908
2 1.3888605507987435
2 1.3888591014359482
2 1.3888576537227841
2 1.3888562076564412
2 1.388854763234111
2 1.3888533204529938
2 1.3888518793102946
2 1.3888504398032269
2 1.3888490019290087
2 1.3888475656848658
2 1.3888461310680276
2 1.3888446980757339
2 1.3888432667052273
2 1.388841836953756
2 1.3888404088185793
2 1.3888389822969593
2 1.3888375573861609
2 1.3888361340834616
2 1.

2 1.3884144379617709
2 1.3884134520290263
2 1.3884124670218216
2 1.3884114829388579
2 1.3884104997788294
2 1.3884095175404365
2 1.3884085362223866
2 1.3884075558233828
2 1.388406576342132
2 1.3884055977773455
2 1.3884046201277371
2 1.388403643392024
2 1.3884026675689207
2 1.3884016926571476
2 1.3884007186554304
2 1.3883997455624915
2 1.388398773377058
2 1.3883978020978605
2 1.388396831723631
2 1.3883958622531045
2 1.388394893685015
2 1.3883939260181073
2 1.3883929592511173
2 1.388391993382791
2 1.3883910284118741
2 1.388390064337114
2 1.3883891011572649
2 1.3883881388710786
2 1.3883871774773078
2 1.3883862169747125
2 1.3883852573620534
2 1.388384298638091
2 1.3883833408015913
2 1.388382383851319
2 1.3883814277860471
2 1.3883804726045463
2 1.3883795183055867
2 1.3883785648879472
2 1.3883776123504052
2 1.3883766606917431
2 1.3883757099107394
2 1.388374760006184
2 1.3883738109768606
2 1.3883728628215604
2 1.3883719155390755
2 1.3883709691281991
2 1.3883700235877265
2 1.388369078916457
2 1

2 1.3880346669955959
2 1.3880340052979223
2 1.388033344108662
2 1.3880326834272325
2 1.3880320232530443
2 1.3880313635855137
2 1.3880307044240565
2 1.3880300457680885
2 1.388029387617029
2 1.3880287299702925
2 1.3880280728272987
2 1.3880274161874722
2 1.3880267600502303
2 1.3880261044149953
2 1.3880254492811894
2 1.3880247946482371
2 1.3880241405155627
2 1.3880234868825911
2 1.388022833748749
2 1.3880221811134643
2 1.3880215289761637
2 1.3880208773362743
2 1.3880202261932302
2 1.3880195755464617
2 1.388018925395396
2 1.3880182757394688
2 1.3880176265781135
2 1.3880169779107618
2 1.388016329736852
2 1.3880156820558143
2 1.3880150348670917
2 1.3880143881701175
2 1.3880137419643326
2 1.3880130962491761
2 1.3880124510240857
2 1.3880118062885052
2 1.3880111620418742
2 1.3880105182836378
2 1.3880098750132364
2 1.3880092322301145
2 1.3880085899337213
2 1.3880079481234988
2 1.388007306798896
2 1.3880066659593597
2 1.388006025604338
2 1.3880053857332808
2 1.3880047463456382
2 1.3880041074408633

2 1.3877464022645607
2 1.3877459434304016
2 1.3877454848893807
2 1.3877450266412192
2 1.3877445686856378
2 1.3877441110223512
2 1.3877436536510825
2 1.3877431965715505
2 1.3877427397834738
2 1.3877422832865738
2 1.3877418270805721
2 1.3877413711651858
2 1.3877409155401428
2 1.3877404602051588
2 1.3877400051599618
2 1.3877395504042696
2 1.3877390959378055
2 1.3877386417602966
2 1.3877381878714625
2 1.3877377342710289
2 1.3877372809587212
2 1.3877368279342601
2 1.3877363751973748
2 1.3877359227477886
2 1.3877354705852265
2 1.3877350187094186
2 1.3877345671200851
2 1.3877341158169583
2 1.387733664799764
2 1.3877332140682248
2 1.3877327636220764
2 1.3877323134610415
2 1.3877318635848503
2 1.3877314139932317
2 1.3877309646859126
2 1.3877305156626272
2 1.3877300669231007
2 1.3877296184670658
2 1.3877291702942527
2 1.3877287224043935
2 1.3877282747972153
2 1.3877278274724554
2 1.387727380429841
2 1.3877269336691072
2 1.3877264871899837
2 1.3877260409922054
2 1.3877255950755056
2 1.38772514943

2 1.3875413961476797
2 1.3875410588747026
2 1.3875407217861768
2 1.3875403848819516
2 1.3875400481618718
2 1.3875397116257884
2 1.3875393752735485
2 1.387539039105004
2 1.3875387031200006
2 1.3875383673183863
2 1.3875380317000165
2 1.3875376962647346
2 1.3875373610123933
2 1.387537025942842
2 1.3875366910559288
2 1.3875363563515066
2 1.3875360218294255
2 1.3875356874895335
2 1.387535353331681
2 1.3875350193557225
2 1.387534685561509
2 1.3875343519488865
2 1.38753401851771
2 1.3875336852678313
2 1.3875333521990993
2 1.3875330193113689
2 1.3875326866044904
2 1.3875323540783158
2 1.3875320217326965
2 1.3875316895674876
2 1.3875313575825383
2 1.3875310257777063
2 1.38753069415284
2 1.3875303627077922
2 1.3875300314424202
2 1.3875297003565725
2 1.3875293694501063
2 1.3875290387228738
2 1.3875287081747287
2 1.3875283778055272
2 1.3875280476151195
2 1.3875277176033625
2 1.3875273877701109
2 1.3875270581152188
2 1.3875267286385422
2 1.3875263993399318
2 1.3875260702192482
2 1.3875257412763435


2 1.3873854834894865
2 1.3873852260476018
2 1.3873849687285307
2 1.3873847115321811
2 1.3873844544584704
2 1.387384197507309
2 1.3873839406786062
2 1.3873836839722773
2 1.3873834273882335
2 1.387383170926387
2 1.387382914586651
2 1.3873826583689346
2 1.3873824022731533
2 1.3873821462992195
2 1.3873818904470459
2 1.3873816347165433
2 1.3873813791076293
2 1.3873811236202103
2 1.3873808682542046
2 1.3873806130095252
2 1.3873803578860797
2 1.3873801028837884
2 1.3873798480025599
2 1.3873795932423092
2 1.3873793386029494
2 1.3873790840843958
2 1.3873788296865608
2 1.387378575409359
2 1.3873783212527027
2 1.3873780672165068
2 1.3873778133006844
2 1.3873775595051503
2 1.3873773058298213
2 1.3873770522746058
2 1.3873767988394237
2 1.387376545524186
2 1.3873762923288093
2 1.3873760392532075
2 1.3873757862972926
2 1.3873755334609852
2 1.3873752807441955
2 1.3873750281468382
2 1.3873747756688322
2 1.3873745233100898
2 1.3873742710705255
2 1.387374018950056
2 1.3873737669485964
2 1.387373515066061

In [126]:
A[2]

array([[0.00186101],
       [0.99904404],
       [0.49832015],
       [0.50081052]])

In [127]:
y

array([[0],
       [1],
       [1],
       [0]])

In [115]:
W

[None, array([[17.6873349 ,  9.70916487],
        [-4.19350785, 12.82126819]]), array([[11.96017793, -9.16184458]])]

In [116]:
b

[None, array([[-0.98956886],
        [ 2.21670246]]), array([[-2.79762586]])]